$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'RMWeatherApp'
  app.info_plist['UIMainStoryboardFile'] = 'MainStoryboard'
end
